### ISSUE TITLE
Strange border around GTK apps

### ISSUE THREAD

**Issue by areyoufeelingitnowmrkrebs** [taj-ny/kwin-effects-forceblur#144] opened 2024-12-19 08:42 UTC
I installed this so that I could make my GTK apps translucent just like my Kvantum ones, getting a weird little border around them though. Not the biggest deal for now but something to look into. Arch btw.
![force blur issue](https://github.com/user-attachments/assets/bec16862-e2cf-4226-917f-09b77c4b3852)

**Comment by taj-ny** [comment] 2024-12-19 08:44
X11? If so, it's a duplicate of #127 and #128 should fix it, it would be nice if you could test that. I'll merge it today.

**Comment by areyoufeelingitnowmrkrebs** [comment] 2024-12-19 08:50
@taj-ny yes X11, I'll try it out and let you know.

**Comment by areyoufeelingitnowmrkrebs** [comment] 2024-12-19 08:52
Didn't realize I would have to install a different version. I'll just wait till the fix makes it's way into the next release.

**Comment by taj-ny** [comment] 2024-12-20 18:13
Should be fixed in v1.3.3.

**Closed by taj-ny** 2024-12-20 18:13 UTC

**Comment by areyoufeelingitnowmrkrebs** [comment] 2024-12-20 18:15
Dope dope. Do you release on a schedule?

**Comment by areyoufeelingitnowmrkrebs** [comment] 2024-12-20 18:25
Hey hear you lol. No worries, I'm just curious 😁
