### ISSUE TITLE
resourceClass and resourceName are not specific enough.

### ISSUE THREAD

**Issue by steviator** [taj-ny/kwin-effects-forceblur#39] opened 2024-04-12 19:34 UTC
Due to the lack of granularity the only useful mode of the application is to have it blur behind all windows all of the time, which causes a massive performance hit. 

Every other application of this type that I've seen has a mechanism to allow more specific matching of Window types making them actually usable.

**Comment by taj-ny** [comment] 2024-04-12 19:41
Duplicate of #25.

**Closed by taj-ny** 2024-04-12 19:41 UTC
